version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: media_postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: media_user
      POSTGRES_PASSWORD: media_password
      POSTGRES_DB: media_db
    ports:
      - "5432:5432"
    volumes:
      - ./STORAGE/postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: media_minio
    restart: always
    env_file: .env
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER: "on"
      MINIO_HTTP_SIZE_LIMIT: "2G"  # Increase MinIO upload limit
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ./STORAGE/minio_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: media_rabbitmq
    restart: always
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./STORAGE/rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    container_name: media_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./STORAGE/redis_data:/data