version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: media_postgres
    restart: always
    environment:
      POSTGRES_USER: media_user
      POSTGRES_PASSWORD: media_password
      POSTGRES_DB: media_db
    ports:
      - "5432:5432"
    volumes:
      - ./STORAGE/postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: media_minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001" # MinIO console
    command: server /data --console-address ":9001"
    volumes:
      - ./STORAGE/minio_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: media_rabbitmq
    restart: always
    ports:
      - "5672:5672"   # RabbitMQ broker
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./STORAGE/rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    container_name: media_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./STORAGE/redis_data:/data
