server:
  port: 8080
  host: "http://localhost:8080"
  tomcat:
    connection-timeout: 60s

spring:
  application:
    name: AstroMediaVault

  web:
    resources:
      static-locations: "D:/DEV/SpringBoot/MediaStreaming/STORAGE/"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:media_db}
    username: ${POSTGRES_USER:media_user}
    password: ${POSTGRES_PASSWORD:media_password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

  # minio:
  #   url: http://${MINIO_HOST:localhost}:9000
  #   access-key: ${MINIO_ACCESS_KEY:minioadmin}
  #   secret-key: ${MINIO_SECRET_KEY:minioadmin}
  #   bucket: media-storage

storage:
  local:
    path: "D:/DEV/SpringBoot/MediaStreaming/STORAGE/"

media:
  pdf:
    max-size-bytes: 115343360 #110MB
  video:
    max-size-bytes: 115343360 #110MB
  img: 
    max-size-bytes: 20971520 #20MB
  
