spring:
  application:
    name: MediaStreaming

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Use 'create' for initial testing, change to 'update' or 'validate' in production
    show-sql: true

  # RabbitMQ configuration
  rabbitmq:
    host: localhost  # Use the container name as the hostname
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    virtual-host: /


  servlet:
    multipart:
      max-file-size: 100MB # Adjust this to your desired maximum file size
      max-request-size: 100MB # Adjust this for the maximum request size

# Media paths configuration
media:
  storage:
    base-path: D:/DEV/SpringBoot/MediaStreaming/STORAGE
    video-path: /videos/original_videos
    image-path: /images
    pdf-path: /pdfs
    segment-path: /videos/segmented


server:
  port: 8050

# Optionally configure logging settings here (if needed)
logging:
  level:
    org.springframework: INFO
    com.media: DEBUG


